stages:
   - build
   - test
   - quality
   - documentation

buildTests:
   stage: build
   script:
      - make test_codeCompletion
   artifacts:
      paths:
         - test_codeCompletion

test:
   stage: test
   script:
      - test_codeCompletion

staticAnalysis:
   stage: quality
   script:
      - make static

style:
   stage: quality
   script:
      - make style

coverage:
   stage: quality
   script:
      - make coverage
   artifacts:
     paths:
        - coverage

memoryLeaks:
   stage: quality
   script:
      - make memcheck

docs:
   stage: documentation
   script:
      - make docs
   artifacts:
      paths:
         - docs
